# Generated by Django 4.1.7 on 2023-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('CountryName', models.CharField(blank=True, db_column='CountryName', max_length=30)),
                ('item', models.CharField(blank=True, max_length=30)),
                ('element', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('CropId', models.AutoField(db_column='CropId', primary_key=True, serialize=False)),
            ],
        ),
    ]
